### PR TITLE
fix: bump package-deps

### LINKED ISSUE #59: Installation fails on 1.54.0 on Windows when Atom is installed in a folder that contains spaces
This is due to a [bug in package-deps.](https://github.com/steelbrain/package-deps/issues/330)
Once it gets fixed on package-deps we must bump deps and ship a new atom-ide-base release.

### PR DESCRIPTION
**Pull request by aminya**
Fixes #59

### CODE REVIEW

**Comment by aminya** [comment]
@deankevorkian Your package-deps update seems to revert what @UziTech fixed. The package tests on Windows fail now.

**Comment by UziTech** [comment]
And linting had been failing for a while.

**Comment by aminya** [comment]
The linting was fixed by #61

**Comment by DeeDeeG** [comment]
Seems to me CI started failing coinciding with the "package-deps 6 to package-deps 7" upgrade: https://github.com/atom-community/atom-ide-base/commit/f64368aafe01d04fba04d799de14298b3a3e453c

**Comment by aminya** [comment]
package-deps 7.2.0 [was fine](https://github.com/atom-community/atom-ide-base/pull/54). The new version reverts @UziTech's [PR](https://github.com/steelbrain/package-deps/pull/329)

**Comment by UziTech** [comment]
The problem is that `"apm"` is not the same thing as `apm` in powershell.

**Comment by UziTech** [comment]
should be fixed in https://github.com/steelbrain/package-deps/pull/332

**Comment by aminya** [comment]
Could you run the tests offline to verify that?

**Comment by UziTech** [comment]
Not sure how to do that

**Comment by DeeDeeG** [comment]
I ran CI on my fork and it passed. ✅ 

---

I think the CI for that repo just installs packages and runs a linter, basically.

https://github.com/steelbrain/package-deps/blob/v7.2.1/.circleci/config.yml#L24-L26

I set authorized Circle CI with my GitHub account, forked and hosted a copy of your `patch-2` branch and ran the CI. It passed.

https://app.circleci.com/pipelines/github/DeeDeeG/package-deps/2/workflows/cb23c0b0-0c98-4b67-a2c3-f368a564199a/jobs/2

(You have to be logged into/authorized with CircleCI to see the results. But I'll copy-paste them below. There are "warnings", but no failures, and there's green checks all the way down all the steps including the lint step.)

<details>

```console
#!/bin/bash -eo pipefail
npm run lint


> atom-package-deps@7.2.1 lint /root/project
> (tsc -p . --noEmit) && (eslint . --ext .ts) && (prettier --list-different src/*.ts)

Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

/root/project/src/helpers/node.ts
  19:30  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  50:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/root/project/src/view/atom.ts
   42:13  warning  Forbidden non-null assertion            @typescript-eslint/no-non-null-assertion
   48:13  warning  Forbidden non-null assertion            @typescript-eslint/no-non-null-assertion
   64:13  warning  Forbidden non-null assertion            @typescript-eslint/no-non-null-assertion
  168:31  warning  'dependency' is defined but never used  @typescript-eslint/no-unused-vars

✖ 6 problems (0 errors, 6 warnings)

CircleCI received exit code 0
```

</details>

**Comment by aminya** [comment]
I meant the atom-ide-base tests. 

> Not sure how to do that

You could run `npm pack` on the package-deps fork, and then install the generated file on this fork
```
cd atom-ide-base
pnpm i package-deps/package-deps-something.tar.gz 
```

Then run the tests:
```
pnpm test
```

**Comment by DeeDeeG** [comment]
https://github.com/DeeDeeG/atom-ide-base/actions/runs/570861601

Looks good, all green. ✅

**Comment by deankevorkian** [comment]
Reverting the change will make the CI work again but will make the package unusable on Windows in spaced paths... I still didn't look at why our ci is falling, you can revert the change in package deps so people won't get the latest version which supposedly has issues. @DeeDeeG and I have tested latest and beta on windows and Mac and didn't encounter any issue. Will have to dive into ci

**Comment by deankevorkian** [comment]
I figured out I missed the change. Quotes have moved from the command itself to the path so working with `shell` doesn't cause any issue.

**Pull request merged**
