### PR TITLE
docs: use docblocks for types

### PR DESCRIPTION
**Pull request by bennypowers**
See #41 and https://github.com/atom-community/atom-community.github.io/pull/8

### CODE REVIEW

**Comment by aminya** [comment]
I am fixing the deps issue in #44

**Comment by aminya** [comment]
@bennypowers Should I release a new npm package for this?

**Review by aminya — APPROVED** [review]

**Comment by bennypowers** [comment]
> @bennypowers Should I release a new npm version for this?

for now I'm using `patch-package` in the docs branch to get these comments in to the wip docs pages, so a release is not crucial.

**Comment by aminya** [comment]
OK. Thanks!

**Pull request merged**
